Handle f courses
KTH/lms-sync-users pull request #87
Opened 2020-09-02 17:32 UTC by miyamoto-san

2020-09-03 08:22 UTC, exacs requested changes
This is not correct.

We have updated the tests to reflect the actual problem in the app (not being able to handle F-courses).

Your task is to fix the code in the app itself so that the fixed test pass. Do not to change the test :)

2020-09-14 22:48 UTC, kaj commented on messages/messageType.js
> +    const isAssistantsRegExp = /edu\.courses\.\w{2,3}\.\w{6,8}\.\d{5}\.\d\.\bassistants\b/
\w{6,7} should be enough, but accepting up to eight chars won't do any harm.

2020-09-15 07:48 UTC, miyamoto-san commented on messages/messageType.js
> +    const isAssistantsRegExp = /edu\.courses\.\w{2,3}\.\w{6,8}\.\d{5}\.\d\.\bassistants\b/
Accepting up to 8 characters is necessary to make the tests work. 7 wasn't enough.

2020-09-15 07:49 UTC, miyamoto-san commented on messages/messageType.js
> +    const isAssistantsRegExp = /edu\.courses\.\w{2,3}\.\w{6,8}\.\d{5}\.\d\.\bassistants\b/
So if 6, 7 works then there's something else that is wrong that probably goes beyond this test?

2020-09-15 08:32 UTC, kaj commented on messages/messageType.js
> +    const isAssistantsRegExp = /edu\.courses\.\w{2,3}\.\w{6,8}\.\d{5}\.\d\.\bassistants\b/
Strange.  Maybe the "random course codes" are still a bit too random?

2020-09-16 08:43 UTC, exacs commented on messages/messageType.js
> +    const isAssistantsRegExp = /edu\.courses\.\w{2,3}\.\w{6,8}\.\d{5}\.\d\.\bassistants\b/
Maybe. I can change the logic (and the test again 😓) to make sure that F-courses are 7 chars

2020-09-16 08:43 UTC, exacs approved these changes

2020-09-16 08:43 UTC, merged