Rewrite
KTH/lms-sync-users pull request #95
Opened 2021-12-01 07:24 UTC by exacs

2021-12-15 14:08 UTC, me97esn commented on test/integration/handleUserMessage.test.js
> +});
I don't like this duplication. We have three tests testing the same thing: first that the response is of type `CREATED USER`, and then test if the result of the `handleMessage` function is actually returning the correct user object. Isn't it better to remove this code from this test function and the two above, and then test this in a separate test function instead?

2021-12-15 14:10 UTC, me97esn commented on test/integration/handleUserMessage.test.js
> +  t.equal(result.user.action, "ignore");
Should these two lines be included in this test? Isn't it enough, and better, to just verify that the user doesn't exist in Canvas? `t.equal(result.user.action, "ignore")` looks like we're testing implementation details, which I don't think belong in an integration test like this

2021-12-15 14:13 UTC, me97esn commented on test/integration/handleUserMessage.test.js
> +  );
This code only tests that the implementation returns an object with `result.user.action, "update"`, which says nothing about if the code actually work. The test _doesn't_ test if the user is actually _updated_, which is the important thing to test imo

2021-12-15 14:14 UTC, me97esn commented on test/integration/handleUserMessage.test.js
> +  );
Same comment as above: this test function doesn't verify that the user has been updated;

2021-12-15 14:16 UTC, me97esn commented on test/integration/messageConsumer.test.js
> +    await deleteTopic(topicName);
Wouldn't this be better suited in a `finally`?

2021-12-15 14:17 UTC, me97esn commented on test/integration/messageConsumer.test.js
> +    await deleteTopic(topicName);
Wouldn't this be better suited in a finally?

2021-12-15 14:22 UTC, me97esn reviewed
I have started by reviewing the tests, since I consider these to be of highest importance. If the tests pass, I feel pretty confident that the implementation works as intended. 

I have some concerns about the tests, perhaps you can look at my comments while I review the implementation?

2021-12-15 14:47 UTC, exacs commented on test/integration/handleUserMessage.test.js
> +  );
Good point!

2021-12-15 14:47 UTC, exacs commented on test/integration/handleUserMessage.test.js
> +  );
Same answer: Good point!

2021-12-15 14:50 UTC, exacs commented on test/integration/handleUserMessage.test.js
> +  t.equal(result.user.action, "ignore");
I think we need to test what is returned by `handleMessage` somewhere. I agree that it is maybe a unit test rather than integration test but we don't have any of those at this moment so I decided to put that check here. I can remove it of course :)

2021-12-15 16:42 UTC, jhsware commented
In general I think the structure is a great improvement! It is also a good step preparing for TS.

2021-12-16 08:23 UTC, me97esn commented on src/messageConsumer.js
> +const CREDIT_INCREMENT = 1;
Since this PR is a major rewrite of the app, we should perhaps change remove the credit handling and instead use a more standard way of consuming messages. The sole reason for manually handling the credits was to make sure that we only consume one message at a time. And the reason for that was that we don't want to consume message in incorrect order (enrolling a user before the user account exist for instance). The error with this design (originally made by me) is that it assumes that the messages are delivered in order, which they are _not_. We are using topics, which have no ordering of messages. So it doesn't matter what our code does, we can't guarantee any message order anyways, and should make the message consuming more standard.

2021-12-16 08:39 UTC, me97esn commented on src/messageConsumer.js
> +      log.error(err, formatErrorMessage(err));
It looks like we do two checks in different locations if the `typecode` exist and is correct. Imo they should be handled in the same place, instead of in two different functions (similar logic is used in `async function receiveMessage(message) {`)

2021-12-16 08:40 UTC, me97esn commented on src/messageConsumer.js
> +  }
See my comment above about doing all of the `typecode` checks in the same location

2021-12-16 10:07 UTC, me97esn commented on src/messageConsumer.js
> +  });
These lines should be removed. We had an idea about how to log statistics, but never got to actually do anything more. This code is just noise.

2021-12-16 10:12 UTC, me97esn commented on src/messageConsumer.js
> +}
This code is a little too complex imo. What happens if we get an error? Is the error thrown _here_, or from the calling code since this function returns a promise that throws an error in the catch function? I honestly am not 100% certain about what the stack trace will look like. Is it possible to make it simpler by using a `try/catch await` instead?

2021-12-16 11:33 UTC, me97esn commented on src/messageConsumer.js
> +  try {
I'm missing a `log.info` about receiving a message. This is something I look at pretty often when debugging, for instance when I'm checking if the system behaves as expected at the beginning of a term.
I would prefer if we logged the exact same line as before this PR (I think it starts with `new message...`), because then we can look at statistics from before this PR is deployed.

2021-12-16 11:40 UTC, me97esn commented on src/messageHandlers/index.js
> +  return { type: "other" };
I notice that this `type:"other"` is never used anywhere. I think it is a good thing to return it just like you to just to make it more readable, but I see a problem with this code: we will never notice when a message is handled as `other`. Which means that any bugs within this function could cause us to miss every message without noticing.
What does `other` mean? Is `type:other` expected or an exception? Should it be logged as a warning or even an error, or perhaps throw an error instead of returning?

2021-12-16 11:44 UTC, me97esn commented on src/messageHandlers/handleUserMessage.js
> +  }
Is this new logic in this PR, or did we have this logic before? I don't remember this use case. Are users without a name a problem?

2021-12-16 11:49 UTC, me97esn commented on src/messageHandlers/handleUserMessage.js
> +    log.info("Message ignored. We don't handle users with these affiliations.");
Minor detail, but I don't like this log line. Since this function delegates the logic of which messages should be handled, I don't think the log should include the word "affiliations" since that is internal logic of the `shouldBeHandled` function

2021-12-16 11:54 UTC, me97esn commented on src/messageHandlers/handleUserMessage.js
> +
I know we had this code before, but perhaps time to change it:
I notice that we create the same object both for updating and creating a user. But according to the comments, some of the data within the object is only used for updating, while other data is only used for creating. Perhaps better to create differend canvasObjects for creating vs updating?

2021-12-16 11:56 UTC, me97esn commented on src/messageHandlers/handleGroupMessage.js
> +  const roleIds = {
I notice that examinator isn't included here, and I can't find any code anywhere handling examinatiors. Shouldn't this app enroll them as well?

2021-12-16 12:01 UTC, me97esn commented on src/messageHandlers/handleGroupMessage.js
> +);
How long does a temp dir live in our server, I have no idea? If this app isn't re-deployed within a few months, is it safe to assume that the temp directory isn't removed during this time? Should we re-design this to create the temp dir when we get a message instead of on start of the app?

2021-12-16 12:09 UTC, me97esn commented on src/messageHandlers/handleGroupMessage.js
> +function getStudentEnrollmentCsvData(group) {
I don't like the names of this, and the other get*EnrollmentCsvData functions. According to the naming standards in other apps (lms-course-rooms-batch for instance) I get the impression that these functions _gets enrollments from LDAP_, which this function doesn't do. But I can't come up with a better name at the moment, because first I have to figure out _what this function actually does_

2021-12-16 13:18 UTC, me97esn commented on src/messageHandlers/handleGroupMessage.js
> +}
This function is really hard to understand from just looking at it. It _really_ looks like it fetches arrays of enrollments from somewhere (LDAP was my guess) for each of the different roles, and then merges all of them together in a flat array. Which is 100% incorrect and is nothing like what it actually does. Can it be rebuilt to make it more obvious how it works?

2021-12-16 13:19 UTC, exacs commented on src/messageHandlers/handleUserMessage.js
> +  }
We had this before: https://github.com/KTH/lms-sync-users/blob/master/messages/handleUserMessage.js#L37

2021-12-16 13:42 UTC, exacs commented on src/messageHandlers/index.js
> +  return { type: "other" };
That's a good question: what does "other" mean? I don't have the answer for that now. We should discuss about it

2021-12-16 13:46 UTC, exacs commented on src/messageHandlers/handleUserMessage.js
> +    log.info("Message ignored. We don't handle users with these affiliations.");
I decided to do the opposite and rename `shouldBeHandled` to `containsHandledAffiliations`. That way "affiliations" is no longer internal logic :)

2021-12-16 13:55 UTC, exacs commented on src/messageHandlers/handleGroupMessage.js
> +);
I don't see this as a problem. Before this PR we were using the `/tmp` directory to create every single file (https://github.com/KTH/lms-sync-users/blob/master/messages/createCsvFile.js#L13) and nothing happened.

2021-12-16 13:56 UTC, exacs commented on src/messageHandlers/handleGroupMessage.js
> +function getStudentEnrollmentCsvData(group) {
I would like to write these functions together

2021-12-16 13:56 UTC, exacs commented on src/messageHandlers/handleGroupMessage.js
> +}
I would like to write these functions together

2021-12-16 14:01 UTC, exacs commented on src/messageConsumer.js
> +  try {
Done https://github.com/KTH/lms-sync-users/pull/95/commits/5631b87d726f987938903b402cfd5e7bd38458d4. However the log line is not here but in the `receiveMessage` function

2021-12-17 07:35 UTC, jhsware requested changes
I added some comments.

2021-12-17 08:20 UTC, me97esn commented on src/messageHandlers/handleGroupMessage.js
> +  const roleIds = {
Actually, after looking at the code in the `main` branch, it looks like we don't handle examinators there either. So this is something that don't have to be fixed within this PR.

2021-12-17 08:21 UTC, me97esn commented on src/messageConsumer.js
> +async function receiveMessage(message) {
Opinions are good, I write a lot of opinions. Then we might not agree upon them, but we should be open to different opinions :)

2021-12-17 08:25 UTC, me97esn commented on test/integration/messageConsumer.test.js
> +const test = require("tape");
I think we did a short run at moving from `tape` to `jest`, but ran into some problems and decided that it wasn't worth it. I think we shouldn't do it in this PR

2021-12-17 08:27 UTC, me97esn commented on src/externalApis/canvasApi.js
> +      throw err;
I agree, but I think it should be outside of this PR. First we should let the errorHandler pattern run in two projects for a while before we duplicate it to more projects.

2021-12-17 08:35 UTC, me97esn commented on src/externalApis/canvasApi.js
> +  throw new Error(
Lol this error will never be thrown! We start by waiting 100 milliseconds, and then double it up to 60 times. Any guess how long time we will have to wait until the error is thrown? (Hint: the last loop will set a timeout of 1 800 000 000 years)

2021-12-17 10:36 UTC, exacs commented on src/externalApis/canvasApi.js
> +  throw new Error(
That's a good point. Hopefully Github Actions will timeout before this test fails :)

2021-12-17 10:39 UTC, exacs commented on src/messageConsumer.js
> +}
I am not sure how should we implement error handling in this app. I would like you (@me97esn and @jhsware) to help me. We could do mob-programming for example.

2021-12-17 10:40 UTC, exacs commented on src/messageConsumer.js
> +      log.error(err, formatErrorMessage(err));
Same error handling problem. The intention here is to separate the action of throwing an error and handling the error. Again, I am open for suggestions because I'm not sure how you (@me97esn @jhsware) want to solve this

2021-12-17 10:41 UTC, exacs commented on src/messageHandlers/handleUserMessage.js
> +
Good point! I can fix it

2021-12-17 10:43 UTC, exacs commented on test/integration/messageConsumer.test.js
> +const test = require("tape");
Anyhow, I would like to not have this discussion in this PR. There are lots of things to fix :)

2021-12-17 11:09 UTC, jhsware commented on src/messageConsumer.js
> +      log.error(err, formatErrorMessage(err));
- Is .error the correct logging level? i.e. is this something we should be alerted of and fix if it occurs?
- I think the flow might be confusing. It appears that "missing_typecode" is something that could occur during normal operation and should be handled immediately in a .catch() clause on the promise.

2021-12-17 11:09 UTC, jhsware commented on src/messageConsumer.js
> +    }
I think this would be more readable as:

`
log.error(err.err || err, formatErrorMessage(err));
`

Also be aware that we won't get a useful stacktrace.

2021-12-17 12:08 UTC, exacs commented on package.json
> +    "debug": "NODE_ENV=development node --nolazy --inspect-brk=9229 . | pino-pretty -o short"
It was a typo :) `-o short` works for bunyan but not for pino-pretty

2021-12-21 14:07 UTC, me97esn commented on src/messageConsumer.js
> +const handleMessage = require("./messageHandlers/handleAllMessages");
I think the names should be changed while we remove logic from the index file. We export a function called `handleAllMessages`, it is exported in a file called `./messageHandlers/index` and we name the variable `handleMessage`. The naming of the file, exported function and variable should be consistent.

2021-12-21 14:10 UTC, me97esn commented on src/messageConsumer.js
> +        err
This creates a _super_ long error in our logs. It can be reproduced by using an invalid Canvas token. It should be fixed before deployment.

2021-12-21 14:11 UTC, me97esn commented on src/messageConsumer.js
> +  log.info("New message", { body: messageBody });
This does _not_ log the messageBody as is expected and wanted behaviour. It only logs the messageId from the message, nothing else.

2022-01-13 10:05 UTC, merged